---
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart ssh

- name: Ensure SSH password authentication is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart ssh

- name: Restart SSH
  service:
    name: ssh
    state: restarted
  listen: Restart ssh
