---
- name: Install required packages
  package:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
      - nginx
    state: present
    update_cache: yes

- name: Clone Flask To-Do app repository
  git:
    repo: "https://github.com/Ajinkya-A3/to-do-app.git"  # Replace with your repo
    dest: /var/www/todo
    version: main

- name: Create Python virtual environment
  command: python3 -m venv /var/www/todo/venv
  args:
    creates: /var/www/todo/venv

- name: Install Python dependencies in virtual environment
  command: /var/www/todo/venv/bin/pip install -r /var/www/todo/requirement.txt
  args:
    chdir: /var/www/todo

- name: Copy index.html if needed
  copy:
    src: index.html
    dest: /var/www/todo/templates/index.html
  ignore_errors: yes

- name: Configure Nginx site
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/todo
  notify: Restart nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/todo
    dest: /etc/nginx/sites-enabled/todo
    state: link
    force: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create systemd service for Flask app
  copy:
    dest: /etc/systemd/system/todo.service
    content: |
      [Unit]
      Description=Flask To-Do App
      After=network.target

      [Service]
      User=www-data
      WorkingDirectory=/var/www/todo
      ExecStart=/var/www/todo/venv/bin/python /var/www/todo/app.py
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Flask app service
  systemd:
    name: todo
    state: started
    enabled: yes

# Handler
- name: Restart nginx
  service:
    name: nginx
    state: restarted
