---
- name: Create devops user
  user:
    name: devops
    groups: sudo
    shell: /bin/bash
    state: present

- name: Add SSH key for devops
  authorized_key:
    user: devops
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
